### ISSUE TITLE
Error running scripts using Julia 1.7.1

### ISSUE THREAD

**Issue by Oi-sin** [Maths-against-Malaria/COVID19_Spatial_Model#1]
Refering to https://twitter.com/Einzigartiger/status/1482971528392237061 

I'm totally new to Julia, thus the problem might be on my side.

I installed Julia 1.7.1 (portable) into an empty directory and tried to run your model scripts on the command line using the latest revision from commit b74aef224cc1e15cc27bc9a3f57817bb79469e88:
```
C:\Temp\COVID19_Spatial_Model-main>c:\temp\julia-1.7.1-win64\bin\julia.exe Spatial_Model_Germany.jl
```

After installing all the required packages as stated in the head of the script I still get the following output:
```
┌ Warning: Assignment to `k1` in soft scope is ambiguous because a global variable by the same name exists: `k1` will be treated as a new local. Disambiguate by using `local k1` to suppress this warning or `global k1` to assign to the existing global variable.
└ @ C:\Temp\COVID19_Spatial_Model-main\Spatial_Model_Germany.jl:1219
ERROR: LoadError: UndefVarError: k1 not defined
Stacktrace:
 [1] top-level scope
   @ C:\Temp\COVID19_Spatial_Model-main\Spatial_Model_Germany.jl:1205
in expression starting at C:\Temp\COVID19_Spatial_Model-main\Spatial_Model_Germany.jl:1202
```
I can solve the error by adding `global ` to line 1219 and the output file will be written to disk. 

I get the same error when running General_Spatial_Model.jl.

As you don't get the error on your side (see above linked Twitter thread), any hints on what might be the problem? Do you need more information?

**Comment by ChristianTsoungui** [comment]
Dear @Oi-sin , thank you for reporting the problem. 

Typically, the issue does not occur when the scripts are run as a block (select the whole script and send to REPL). However, whenever the scripts are not run as a block, there was indeed a problem with the definition of some of the variable for which the scope (global vs local) was not clear for the compiler. 

We fixed the issue by clarifying the definition local/global for those ambiguous variables. The script now runs as it should, independently of the method used to execute it.

**Comment by ChristianTsoungui** [comment]
@Oi-sin, since this issue has been addressed, I will close it. Thanks again for pointing the problem out.

**Comment by Oi-sin** [comment]
I can confirm, that the issue is solved. Works for me :-). Thanks a million!

**Comment by ChristianTsoungui** [comment]
> I can confirm, that the issue is solved. Works for me :-). Thanks a million!

Dear @Oi-sin you are most welcome. Thank you for your interest in our model.
